[2025-09-03T23:55:21.961+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T23:55:22.047+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_pipeline.extract_postgres scheduled__2025-09-02T07:35:00+00:00 [queued]>
[2025-09-03T23:55:22.060+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_pipeline.extract_postgres scheduled__2025-09-02T07:35:00+00:00 [queued]>
[2025-09-03T23:55:22.061+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-03T23:55:22.081+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_postgres> on 2025-09-02 07:35:00+00:00
[2025-09-03T23:55:22.090+0000] {standard_task_runner.py:64} INFO - Started process 261 to run task
[2025-09-03T23:55:22.098+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_pipeline', 'extract_postgres', 'scheduled__2025-09-02T07:35:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/banvic_pipeline.py', '--cfg-path', '/tmp/tmpy8ezlzx0']
[2025-09-03T23:55:22.101+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask extract_postgres
[2025-09-03T23:55:22.340+0000] {task_command.py:426} INFO - Running <TaskInstance: banvic_pipeline.extract_postgres scheduled__2025-09-02T07:35:00+00:00 [running]> on host 644a78dce44d
[2025-09-03T23:55:22.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='banvic_pipeline' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T07:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T07:35:00+00:00'
[2025-09-03T23:55:22.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T23:55:22.657+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-03T23:55:22.659+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/project/scripts/extracao_postgres/extracao_completa.py']
[2025-09-03T23:55:22.670+0000] {subprocess.py:86} INFO - Output:
[2025-09-03T23:55:24.114+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-03T23:55:24.115+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/extracao_postgres/extracao_completa.py", line 12, in <module>
[2025-09-03T23:55:24.122+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-09-03T23:55:24.125+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-09-03T23:55:24.126+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-09-03T23:55:24.127+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 55432 failed: Connection refused
[2025-09-03T23:55:24.128+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-09-03T23:55:24.129+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 55432 failed: Connection refused
[2025-09-03T23:55:24.130+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-09-03T23:55:24.131+0000] {subprocess.py:93} INFO - 
[2025-09-03T23:55:24.284+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-03T23:55:24.286+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T23:55:24.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-03T23:55:24.391+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=banvic_pipeline, task_id=extract_postgres, run_id=scheduled__2025-09-02T07:35:00+00:00, execution_date=20250902T073500, start_date=20250903T235522, end_date=20250903T235524
[2025-09-03T23:55:24.454+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task extract_postgres (Bash command failed. The command returned a non-zero exit code 1.; 261)
[2025-09-03T23:55:24.495+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-03T23:55:24.629+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T23:55:24.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
