[2025-09-04T00:44:34.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-04T00:44:34.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_pipeline.load_dw manual__2025-09-04T00:34:15.908726+00:00 [queued]>
[2025-09-04T00:44:34.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_pipeline.load_dw manual__2025-09-04T00:34:15.908726+00:00 [queued]>
[2025-09-04T00:44:34.640+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-04T00:44:34.656+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_dw> on 2025-09-04 00:34:15.908726+00:00
[2025-09-04T00:44:34.661+0000] {standard_task_runner.py:64} INFO - Started process 358 to run task
[2025-09-04T00:44:34.666+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_pipeline', 'load_dw', 'manual__2025-09-04T00:34:15.908726+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/banvic_pipeline.py', '--cfg-path', '/tmp/tmp6dotw4um']
[2025-09-04T00:44:34.669+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask load_dw
[2025-09-04T00:44:34.839+0000] {task_command.py:426} INFO - Running <TaskInstance: banvic_pipeline.load_dw manual__2025-09-04T00:34:15.908726+00:00 [running]> on host 8ecc11fed1c2
[2025-09-04T00:44:35.041+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='banvic_pipeline' AIRFLOW_CTX_TASK_ID='load_dw' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T00:34:15.908726+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T00:34:15.908726+00:00'
[2025-09-04T00:44:35.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-04T00:44:35.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-04T00:44:35.057+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/project && python scripts/load_dw.py']
[2025-09-04T00:44:35.068+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T00:44:35.379+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-04T00:44:35.380+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/load_dw.py", line 103, in <module>
[2025-09-04T00:44:35.383+0000] {subprocess.py:93} INFO -     main()
[2025-09-04T00:44:35.384+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/load_dw.py", line 63, in main
[2025-09-04T00:44:35.388+0000] {subprocess.py:93} INFO -     conn = get_dw_conn()
[2025-09-04T00:44:35.388+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/load_dw.py", line 29, in get_dw_conn
[2025-09-04T00:44:35.390+0000] {subprocess.py:93} INFO -     return psycopg2.connect(
[2025-09-04T00:44:35.391+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-09-04T00:44:35.391+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-09-04T00:44:35.392+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 56432 failed: Connection refused
[2025-09-04T00:44:35.392+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-09-04T00:44:35.393+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 56432 failed: Connection refused
[2025-09-04T00:44:35.393+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-09-04T00:44:35.394+0000] {subprocess.py:93} INFO - 
[2025-09-04T00:44:35.396+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-04T00:44:35.398+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-04T00:44:35.433+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-04T00:44:35.438+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=banvic_pipeline, task_id=load_dw, run_id=manual__2025-09-04T00:34:15.908726+00:00, execution_date=20250904T003415, start_date=20250904T004434, end_date=20250904T004435
[2025-09-04T00:44:35.481+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task load_dw (Bash command failed. The command returned a non-zero exit code 1.; 358)
[2025-09-04T00:44:35.523+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-04T00:44:35.574+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T00:44:35.578+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
