[2025-09-03T23:55:26.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T23:55:26.833+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banvic_pipeline.extract_transacoes manual__2025-09-03T23:50:14.906018+00:00 [queued]>
[2025-09-03T23:55:26.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banvic_pipeline.extract_transacoes manual__2025-09-03T23:50:14.906018+00:00 [queued]>
[2025-09-03T23:55:26.867+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-03T23:55:26.897+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_transacoes> on 2025-09-03 23:50:14.906018+00:00
[2025-09-03T23:55:26.912+0000] {standard_task_runner.py:64} INFO - Started process 292 to run task
[2025-09-03T23:55:26.925+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'banvic_pipeline', 'extract_transacoes', 'manual__2025-09-03T23:50:14.906018+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/banvic_pipeline.py', '--cfg-path', '/tmp/tmpa4dkj3n9']
[2025-09-03T23:55:26.932+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask extract_transacoes
[2025-09-03T23:55:27.250+0000] {task_command.py:426} INFO - Running <TaskInstance: banvic_pipeline.extract_transacoes manual__2025-09-03T23:50:14.906018+00:00 [running]> on host 644a78dce44d
[2025-09-03T23:55:27.755+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='banvic_pipeline' AIRFLOW_CTX_TASK_ID='extract_transacoes' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T23:50:14.906018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T23:50:14.906018+00:00'
[2025-09-03T23:55:27.757+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T23:55:27.778+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-03T23:55:27.797+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/project/scripts/extracao_csv/extracao_transacoes.py']
[2025-09-03T23:55:27.810+0000] {subprocess.py:86} INFO - Output:
[2025-09-03T23:55:29.327+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-03T23:55:29.328+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/extracao_csv/extracao_transacoes.py", line 28, in <module>
[2025-09-03T23:55:29.334+0000] {subprocess.py:93} INFO -     main()
[2025-09-03T23:55:29.336+0000] {subprocess.py:93} INFO -   File "/opt/airflow/project/scripts/extracao_csv/extracao_transacoes.py", line 10, in main
[2025-09-03T23:55:29.344+0000] {subprocess.py:93} INFO -     raise FileNotFoundError(f"Arquivo {ARQUIVO_FONTE} não encontrado na raiz do projeto.")
[2025-09-03T23:55:29.346+0000] {subprocess.py:93} INFO - FileNotFoundError: Arquivo transacoes.csv não encontrado na raiz do projeto.
[2025-09-03T23:55:29.454+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-03T23:55:29.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T23:55:29.533+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-03T23:55:29.538+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=banvic_pipeline, task_id=extract_transacoes, run_id=manual__2025-09-03T23:50:14.906018+00:00, execution_date=20250903T235014, start_date=20250903T235526, end_date=20250903T235529
[2025-09-03T23:55:29.597+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task extract_transacoes (Bash command failed. The command returned a non-zero exit code 1.; 292)
[2025-09-03T23:55:29.643+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-03T23:55:29.731+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
